"""
Surface gateway schemas for the autonomous diver companion prototype.

These models represent the operator-facing status produced by the simulated
surface gateway after receiving robot status reports.
"""

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field

from shared.robot_protocol import RobotStatusPacket


class SurfaceMissionState(str, Enum):
    NO_ROBOT_REPORT = "NO_ROBOT_REPORT"
    AWAITING_DIVER_DATA = "AWAITING_DIVER_DATA"
    NORMAL = "NORMAL"
    ATTENTION_REQUIRED = "ATTENTION_REQUIRED"
    EMERGENCY = "EMERGENCY"
    DIVER_DATA_STALE = "DIVER_DATA_STALE"

class SurfaceAlert(BaseModel):
    """
    Operator-facing alert generated by the surface gateway.
    """

    code: str = Field(min_length=1)
    message: str = Field(min_length=1)
    priority: int = Field(ge=0, le=100)


class SurfaceGatewayState(BaseModel):
    """
    Current state of the surface gateway.

    This combines the latest robot report with the surface-side mission state
    and any operator-facing alerts.
    """

    latest_robot_report: RobotStatusPacket | None = None
    reports_received: int = Field(default=0, ge=0)

    mission_state: SurfaceMissionState
    alerts: list[SurfaceAlert] = Field(default_factory=list)
